# Generated by Django 3.1 on 2020-09-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managegoal', '0004_auto_20200926_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='lat',
            field=models.FloatField(null=True),
        ),
    ]
