# Generated by Django 3.1 on 2020-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managegoal', '0005_prefecture_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
