# Generated by Django 3.1 on 2020-09-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managegoal', '0006_prefecture_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeapplication',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changedhistory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impression',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
