# Generated by Django 3.1 on 2020-10-03 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managegoal', '0008_auto_20201003_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeapplication',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_changeapp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changeapplication',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='changeapplication',
            name='good_users',
            field=models.ManyToManyField(related_name='good_users_changeapp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='impression',
            name='good_users',
            field=models.ManyToManyField(related_name='good_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
