# Generated by Django 3.1 on 2020-10-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managegoal', '0009_auto_20201003_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeapplication',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='changeapplication',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='changeapplication',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
