# Generated by Django 3.1 on 2020-10-16 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managegoal', '0012_auto_20201016_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='favo_users',
            field=models.ManyToManyField(related_name='favo_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
