# Generated by Django 3.1 on 2020-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', models.CharField(max_length=100)),
            ],
        ),
    ]
