# Generated by Django 3.1 on 2020-09-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0002_aaa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AAA',
        ),
    ]
